title: Fabrizio Montesi's Blog
email: famontesi@gmail.com
# description: > # this means to ignore newlines until "baseurl:"
#
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fmontesi.github.io" # the base hostname & protocol for your site
twitter_username: famontesi
github_username:  fmontesi

# Build settings
markdown: kramdown
